### ISSUE TITLE
Missing favicon

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/GraphOmics#108]
Not sure where this came from ...

![image](https://user-images.githubusercontent.com/2523391/122958134-7f4aa000-d37a-11eb-8caa-8c10f6b50f46.png)

**Comment by RonanDaly** [comment]
Do you mean the mangled URL? Probably just a chrome issue.

**Comment by joewandy** [comment]
just wondering where the reference to `favicon.ico` came from, since there's nothing in our codes that use that.

**Comment by RonanDaly** [comment]
Oh that's just a default browser setting.
