### ISSUE TITLE
Website gives a 502 Bad Gateway error

### ISSUE THREAD

**Issue by dpanyard** [glasgowcompbio/GraphOmics#131]
**Describe the bug**
The website for the [app](https://graphomics.glasgowcompbio.org/app/) does not work. It gives a 502 Bad Gateway error.

**To Reproduce**
1. Go to [https://graphomics.glasgowcompbio.org/app/](https://graphomics.glasgowcompbio.org/app/)
2. See error

**Expected behavior**
Working link.

**Screenshots**
![image](https://github.com/user-attachments/assets/ba8076de-5ba2-41da-9adb-ff0e39cc1458)

**Desktop (please complete the following information):**
 - Browser [e.g. Chrome or Firefox]

**Additional context**
N/A

**Comment by joewandy** [comment]
Server seems to be up now, and have notified @dpanyard about it.
