### ISSUE TITLE
Export function

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/GraphOmics#14]
We need an exporting function

1. In each individual table, add a datatable export button for each data type
2. In the summary page, add a global export button. Maybe we can export a networkx object that can be loaded back to Cytoscape.

**Comment by RonanDaly** [comment]
Is it possible to export to Reactome? Perhaps overlay the data?

**Comment by joewandy** [comment]
If we just want to overlay the data, we should just incorporate their diagram widget directly in our app https://reactome.org/dev/diagram/js. Working on that now.

**Comment by joewandy** [comment]
Initial diagram integration done in https://github.com/joewandy/WebOmics/commit/32e1d04598cc325165a76846f1f6ede17902e11e

**Comment by joewandy** [comment]
Diagram integration only works for pathway data, so we should hide the magnifying glass buttons from the transcript, protein, compound and reaction panels.

![Inkedinfo_panel_LI](https://user-images.githubusercontent.com/2523391/69725881-23288700-1117-11ea-9beb-404d6dc31dea.jpg)

**Comment by joewandy** [comment]
The diagram tool allows us to set an analysis token, which can be used to overlay analysis results previously submitted to Reactome Analysis Service.

See:
- https://reactome.org/dev/pathways-overview/js
- https://reactome.org/dev/analysis

However it isn't clear how the layout is done. For example, manually submitting the intensity information of the following compound (IMP) 

![image](https://user-images.githubusercontent.com/2523391/75169971-503e0300-5721-11ea-8ba2-c57eea2b0aaa.png)

results in the following overlay for IMP in the pathway diagram:

![image](https://user-images.githubusercontent.com/2523391/75169870-2c7abd00-5721-11ea-8718-28faaf68f187.png)

Maybe it's taking the average of the submitted intensity values?

**Comment by joewandy** [comment]
Add another page to link comparisons across different omics type. We can then use this to send the right data (fold change) across all the different omics at once to Reactome Analysis Service.

**Comment by joewandy** [comment]
Final commit in https://github.com/joewandy/WebOmics/commit/f5793c41eb3f0b94a79f2ca309e7c184d7f91735.
