### ISSUE TITLE
Boxplots for metabolites don't show up

### ISSUE THREAD

**Issue by RonanDaly** [glasgowcompbio/GraphOmics#39]
The box plots for metabolites don't show when "Show measurements" is clicked. This happens when only metabolite data is loaded - it does not occur when transcriptomics and metabolomics data are both loaded. Test with ArchiveStandard.zip.

**Comment by joewandy** [comment]
The width of the boxplot was dependant on the width of the gene column. When the gene column was hidden, the boxplot width became 0.

Now the width is fixed to 250px.
