### ISSUE TITLE
Large memory requirement to run WebOmics

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/GraphOmics#43]
> I'm trying to load WebOmics and the python process is taking up ~ 1.3 GB, before any queries have been run. Does this make sense to you?

Probably due to this:
https://github.com/joewandy/WebOmics/blob/master/web_omics/linker/constants.py#L6-L9

Should try to make it so these are loaded only when needed.

It might make an analysis slower to submit. We probbably need to add some kind of progress bar when submitting an analysis (so users don't think it's hanging).

**Comment by RonanDaly** [comment]
Fixed in 473ecce219b8980a971e095faeaf651f62aea1ef
