### ISSUE TITLE
Fix https on localhost

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/GraphOmics#94]
Whenever i visit http://localhost:8000 on development, i got sent to https://localhost:8000/, and received the error message:

![image](https://user-images.githubusercontent.com/2523391/118141609-72dd3a00-b401-11eb-8a16-72fc6292895e.png)

Fix:
https://stackoverflow.com/questions/35536491/error-youre-accessing-the-development-server-over-https-but-it-only-supports/35536980

**Comment by RonanDaly** [comment]
The config for this is currently under Development instead of Production - why is this?

**Comment by joewandy** [comment]
It was done in a hurry ... sorry
